name: xcap
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - ld_impl_linux-64
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.6.13
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - anyio==2.2.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - babel==2.9.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.5
    - chardet==4.0.0
    - contextvars==2.4
    - cycler==0.10.0
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.10
    - immutables==0.15
    - importlib-metadata==3.7.0
    - ipykernel==5.5.0
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-core==4.7.1
    - jupyter-packaging==0.7.12
    - jupyter-server==1.4.1
    - jupyterlab==3.0.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.3.0
    - kiwisolver==1.3.1
    - lightgbm==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclassic==0.2.6
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - numpy==1.19.5
    - packaging==20.9
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.8.1
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.16
    - ptyprocess==0.7.0
    - pybigwig==0.3.18
    - pycparser==2.20
    - pygments==2.8.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyzmq==22.0.3
    - requests==2.25.1
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - seaborn==0.11.1
    - send2trash==1.5.0
    - six==1.15.0
    - sniffio==1.2.0
    - statsmodels==0.12.2
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tornado==6.1
    - tqdm==4.58.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - zipp==3.4.0
